### PR TITLE
Redirect current page

### PR DESCRIPTION
**Pull request by germanBonacchi**
#### What problem is this solving?

When you use the bindigs selector always redirects to the home after change the bindig.

We add the `redirectPage` to enable to redirect to the current page you are using.

#### How to test it?

[Workspace](https://gbo--beautycounterqa.myvtex.com/)

#### Screenshots or example usage:

image
image

### CODE REVIEW

**Comment by germanBonacchi** [comment]
I update manually the version to 2.2.0

**Comment by filafb** [comment]
Hi @germanBonacchi. Thanks for the PR. The app is already designed to redirect the shoppers to the right page when the alternates href are set. [Here](https://github.com/vtex-apps/binding-selector/blob/574f4abd0ecf6581fcd21897401fe0b36bcfbbd3/react/BindingSelectorBlock.tsx#L57-L62) is the request where the app gets these values.
The app only redirects to home when the alternates are not there. 
We use this approach to ensure stores that have theirs URLs in different languages are correctly redirected - for example: when changing from a page in Italian to the Spanish version, the app cannot use the same pathname because the product will have different slugs. That means you can have the product page URL in French to improve SEO.

To generate the alternates href for different bindings for the products, you can try:
1. Have the [broadcaster-worker app](https://github.com/vtex-apps/broadcaster-worker) installed in the account;
2. Hit the endpoint to trigger the routes indexation: `https://app.io.vtex.com/vtex.broadcaster-worker/v0/:accountName/:workspace/index-routes`.

To check the alternates for you pages, you can use the graphql-ide in the admin and run the following query:
```
query alternateHrefs($id: String!, $type: String!) {
  internal {
    routes(locator: { id: $id, type: $type }) {
      binding
      route
    }
  }
}

variables:
{
  "id": {{productId}},
  "type": "product"
}
```

**Comment by germanBonacchi** [comment]
@filafb In our client case the url of the products doesn't change between languages.

The main problem is that the client always needs the language selector to leave it on the screen that the client was browsing.

According with your solution we will need to create the internal routes to all our routes, including products and static urls.

**Comment by filafb** [comment]
The routes for products, brands and categories are all created for the different bindings. You might have issues if you are using the automatic translations. If so, you can use the catalog translation app to assign the link id you wish. Regarding the static pages, if the pages were created for the different bindings using the same URL, they should be already an alternate for the different bindings. I think we should stick with the href alternates as the source of truth for the redirects.

@Git-the-Sanz @lrodriguess WDUT?

**Pull request closed without merging**
